# Generated by Django 3.0.6 on 2020-05-14 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0009_likemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
