# Generated by Django 3.0.6 on 2020-05-14 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0012_auto_20200514_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
