# Generated by Django 3.0.6 on 2020-05-16 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0014_auto_20200514_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
